version: '2'
services:
    ministering-app:
        image: ministering
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ministering-mysql:3306/ministering?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=ministering-elasticsearch:9300
        ports:
            - 8001:8080
    ministering-mysql:
        extends:
            file: mysql.yml
            service: ministering-mysql
    ministering-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ministering-elasticsearch
